name: NetheriteLimiter
main: com.xpoesem.nthirite.NetheriteLimiter  # Ensure this points to the correct main class
version: 1.0
api-version: 1.20
description: Limits Netherite Armor to only one set in the world.
