name: NetheriteLimiter
main: com.michael.netheritelimiter.NetheriteLimiter  # Replace this with your actual package name and class
version: 1.0
api-version: 1.20
description: Limits Netherite Armor to only one set in the world.
